FAC documentation updates
shipyardapp/Shipyard-Documentation pull request #100
Opened 2022-02-25 20:44 UTC by forstmeier

2022-03-01 16:48 UTC, blakeburch requested changes

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +Vessels may have `_id` and `_ref` top-level fields.
I vote not even making mention of the _ref fields. I think it adds unneeded complexity from an editing perspective... and we don't reveal it in the UI right now.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `file_to_run` is a string representing the file to for any Vessel type that requires it
Confusing statement. I would also indicate that if you choose the combination of source type: code with file, the value will most likely be the same as the file `name`.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `blueprint` is the name of the Blueprint created separately from the Fleet - it must match the name exactly and may either be a [Shipyard Blueprint](blueprint-library/blueprint-library-overview.md)
Library Blueprint, not Shipyard Blueprint.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `inputs` are a key-value pair representing the [input variable](inputs/blueprint-variables.md) name and value - if the Blueprint is configured so that the input is a "password" type, when this FAC
I would specify this further. It maps up to the Reference Name for any Blueprint input. The example should show a clear translation of an actual Library Blueprint (with a link to the docs so it's a bit more obvious where the reference_name values came from).

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +  arguments:
Arguments and environment variables are provided as lists of key/value. I would make sure the example demonstrates that.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +	  version: '1.0.0'
I think the version will always need to be something like `==1.0.0`. Just want to make sure the example doesn't throw someone off.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +
Needs the example.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `runtime_cutoff` is a string representing the amount of time to wait before killing a Vessel (max of 1h) - the example above indicates a runtime cutoff of 5 minutes and 30 seconds
Max is 4h. 

For this and retry_wait, I would make sure to explain the formatting must be a string of ##h##m##s and make sure the examples cover the gambit of options there.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `emails` is an array of email addresses to send notifications to
Make sure the example shows 2 emails so it's clear how the array needs to be formatted.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +- `after_error` is a boolean indicating whether to send a notification after a Vessel fails
Instead of fails, I would make sure to use consistent language of "after a Vessel completes with a [status](https://www.shipyardapp.com/docs/reference/other-functions/status/#vessel-statuses) of Errored"

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +Each key in the object is a Vessel name or `_ref` value (if provided) representing the "from" Vessel and the value is an object that contains the "to" Vessel(s) and the connection type. See below for
remove _ref

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +This example indicates that if `vessel_one` succeeds, it will invoke `vessel_two` and if `vessel_two` succeeds, it will invoke `vessel_three`. If `vessel_two` fails, it will invoke `vessel_four`.
I would put a screenshot here. That will be clearer.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +This is the same object available under the Vessels `notifications` field. If configured, this will emit notifications based on actions of the full Fleet.
Still provide the example YAML.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fac.md
> +Below is a full example FAC file.
I would like to update the example to have more indentation (I think 4 vs 2) so it's clearer.

I also think providing an additional empty template YAML with comments would be helpful.

2022-03-01 16:48 UTC, blakeburch commented on docs/reference/fleets.md
>  ## Screenshots
I would add a screenshots of the YAML editor here.

2022-03-03 03:15 UTC, blakeburch commented on docs/reference/fac.md
> +In these examples there are four schedules set on the Fleet.
Need to specify that the times have to be in 24:00 hour time, with at least one example that demonstrates it (replace an existing time)

2022-03-07 15:00 UTC, forstmeier commented on docs/reference/fac.md
> +Below is a full example FAC file.
Do we need another whole one? I'd either push them towards the app where we have that stuff being generated or remove the values from this one and just make it a commented template - two is a lot it feels like.

2022-03-07 16:01 UTC, blakeburch commented on docs/reference/fac.md
> +
Tabbed makes sense for write/upload/blueprint. But it doesn’t make sense for the sections that are consistent across those (even though they are all optional) _(with Axolo)_

2022-03-07 16:04 UTC, blakeburch commented on docs/reference/fac.md
> +Below is a full example FAC file.
Yes, we want to push them towards the UI. But we also want to meet them where they’re currently at if they’re reading the docs.

I still think there should be both a blank template example (with comments) and a fully filled out template example. You’re right that the blank template should practically mirror what the UI starts people with. _(with Axolo)_

2022-03-08 14:25 UTC, blakeburch commented
Forgot to mention this one. We should make note somewhere that right now comments will never be saved/re-shown.

2022-03-08 16:23 UTC, forstmeier commented
@blakeburch I added that in by the example.

2022-03-14 14:14 UTC, katthartic commented on docs/reference/fac.md
> +"Fleets As Code" ("FAC") is a YAML-based definition of a Shipyard [Fleet](fleets.md). This system allows for users to take a more code-based approach to constructing their workflow definitions. Addit
@forstmeier Here!

2022-03-14 18:56 UTC, ericelsken commented
What's the status on this? When is going out, after the Shipyard org flag removal?

2022-03-14 19:17 UTC, forstmeier commented
Yes, once the full feature is available to everyone we'd publish this documentation update.

2022-03-16 20:40 UTC, merged