Documentation Changes
shipyardapp/Shipyard-Documentation pull request #122
Opened 2022-05-09 13:41 UTC by smjohnsonShipyard

Changed tutorials into a getting started section and tutorial section.

2022-05-11 19:13 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +
Place the extra text of "If you have not....... in this tutorial" in a :::caution before the steps (same as the other tutorials)

2022-05-11 19:17 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +### Build HTTP Download File Vessel
I think it's clearer to just indicate what's being done.

"Build Vessel to Download File via HTTP"

Thoughts?

2022-05-11 19:18 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +### Build Send Email Message with File Vessel
Same thing here.

"Build Vessel to Email a File"

Thoughts?

2022-05-11 19:19 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +2.  Search for **email** using the search bar at the top. Click on **Send Message with File**
Clever! I really like showing them both ways to do it in different directions.

2022-05-11 19:21 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +6.  Click the **Save** button at the bottom.
Save & Finish

2022-05-11 19:22 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +6.  Click the **Save** button at the bottom.
Actually, scratch that. Remove this here and have the instruction to Save & Finish after editing the Fleet Name.

2022-05-11 19:23 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +
Screenshot should probably show those Vessels on the graph.

2022-05-11 19:24 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +2. Rename your fleet to Download File from Webpage and Email to User. Notice that the project is pre-selected from our actions in Step 1 above.
Specify the field to select for this, just as you did earlier.

2022-05-11 19:24 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +3. After completing the settings, navigate back to **add vessel** by using the Fleet Builder sidebar.
I would scratch this step and just have them save. This will redirect to the "Success" page, which Step 4 should build off.

2022-05-11 19:26 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +1. Click **Run Now** on the top-right corner of the Fleet Builder.
Edit to do it from the Success page. Emphasize with a note that you can always click the "Run Now" button in the top-right corner to do the same thing.

2022-05-11 19:30 UTC, blakeburch requested changes
General comment:

-  Any Shipyard specific elements, we capitalize.  Fleet, Blueprint, Vessel, etc. If it’s a generic, it’s a tossup. log, project, user, etc.

Should be able to find/replace quickly with regex.

2022-05-11 21:16 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +## Step 3 - Setting Up the Fleet
This entire step should contain tabs as well. The current explanation is for Graph. You should also explain how to rename the Fleet in the YAML.

2022-05-11 21:18 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +2. Replace the code in the editor with the YAML code below.
Thoughts on actually walking the user through adding the Vessels using the sidebar and filling in the blanks on the YAML editor?

We could still have a thing that says "If you don't want to walk through these setup steps, "copy/paste this code" but it feels disingenuious to not walk the user through the steps.

2022-05-11 21:21 UTC, blakeburch commented on docs/getting-started/first-vessel-with-code.md
> +3. Shipyard allows you to provide code to run in the service in three different ways: write the code in service, upload the code as a file, or get the code from a Github repository. This tutorial wil
Use "in the UI" instead of "in service".

Also, it feels like this explanation blurb should be before the entire tutorial. Steps should minimize explanation.

2022-05-11 21:24 UTC, blakeburch commented on docs/getting-started/first-vessel-with-code.md
> +### Step 3 - Requirements
Call this "Install Python Packages"

2022-05-11 21:24 UTC, blakeburch commented on docs/getting-started/first-vessel-with-code.md
> +1. Find the **Python Packages** drop down in your vessel's settings and click on it to show the package installer.
On the Fleet Builder, we reference each of these sections as "Panels", not a "Dropdown".

2022-05-11 21:26 UTC, blakeburch commented on docs/getting-started/first-vessel-with-code.md
> +The version field can accept three types of arguments: >, <, and ==. You can use these three options to be as specific as you want to specific package version
Actually not true. It can also support >=, <=, !=, ~, etc. 

I would instead list your options but also link to the external-package-dependencies page that shows what's allowed for each language.

2022-05-11 21:29 UTC, blakeburch commented on docs/getting-started/first-vessel-with-code.md
> +
This is actually the Fleet Log

2022-05-11 21:34 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +![Connect Vessels](../gitbook/assets/../../.gitbook/assets/connecting_vessels.gif)
Before this can happen, the Vessels get stacked on top of each other. May be worth mentioning that you can move them around, then connect. Show that in the gif.

2022-05-11 21:36 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +2. Rename your fleet to Download File from Webpage and Email to User. Notice that the project is pre-selected from our actions in Step 1 above.
Also, might be worth a cutesier name like "Disney Ride Wait Alerts"

2022-05-11 21:45 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +_id: 38bc6d23-3c0d-41cc-a300-6f77a484f42b
This example needs to remove all `_ids` to be created as a new Fleet.

2022-05-11 21:46 UTC, blakeburch commented on docs/getting-started/first-fleet.md
> +                - steven.johnson@shipyardapp.com
if we do pure copy/paste we should have it go to something generic like tutorials@shipyardapp.com unless you want spam. :)

2022-05-12 14:13 UTC, smjohnsonShipyard commented on docs/getting-started/first-fleet.md
> +### Build HTTP Download File Vessel
agreed

2022-05-13 15:15 UTC, blakeburch approved these changes

2022-05-13 15:18 UTC, merged