Add version control documentation
shipyardapp/Shipyard-Documentation pull request #129
Opened 2022-06-10 18:41 UTC by katthartic

2022-06-10 19:06 UTC, blakeburch requested changes
General comments:

1) I don't think we need separate pages. A single sidebar button for "Version Control" and just combine your two pages together in a logical way.
2) Add something to the Fleet reference page that indicates that Fleets are version controlled every time a user clicks "Save". (link out to version control)
3) There's a section of Reference/Vessels that talks about version control. Make sure that's accurate, or at least specifies the difference between Project Vessels and Vessels that are part of a Fleet.

2022-06-10 19:06 UTC, blakeburch commented on docs/reference/version-control/version-cards.md
> +The YAML-based definition of a Shipyard Fleet is generated from the Fleet's underlying JSON rather than being stored as a file. For this reason, Vessels within the Fleet's YAML can sometimes display
Make this clearer for the user. 1) They don't know about the "underlying JSON". 2) I don't think the order can change, since it alphabetizes the list. The way it's written right now sounds like it's inaccurate.

2022-06-10 19:06 UTC, blakeburch commented on docs/reference/version-control/version-control-overview.md
> +
> viewing/editing
viewing or editing (avoid `/`)

> A version is created each time you save a Fleet
Every time you save a Fleet, a new version number will be created that increments the current version number by one.

2022-06-10 19:08 UTC, katthartic commented on docs/reference/version-control/version-control-overview.md
> +
Got it! We have it elsewhere so I thought it was standard. Would you like me to remove it if I see it in other places as well?

2022-06-10 19:40 UTC, blakeburch commented on docs/reference/version-control/version-control-overview.md
> +
confirming in writing, yes _(with Axolo)_

2022-06-10 21:23 UTC, katthartic commented
@blakeburch This is ready for another look.

2022-06-10 21:37 UTC, blakeburch submitted a review, later dismissed

2022-06-14 15:26 UTC, blakeburch submitted a review, later dismissed

2022-06-15 19:29 UTC, blakeburch approved these changes

2022-06-15 19:41 UTC, merged