Update version and redirects 07262022
shipyardapp/Shipyard-Documentation pull request #144
Opened 2022-07-28 15:49 UTC by blakeburch

This PR looks like a lot got updated. It was mostly moving things around.

- Removes all references to Vessel tabs and wizard. Doing this preemptively before we remove the old Vessel flow altogether.
- Updates the folder/sidebar structure to mirror the current breakout of panels (no settings folder, no requirements folder, etc.)
- Updates all broken links as a result of changing the structure.
- Quick pass at removing any old, invalid, or inaccurate statements and updating screenshots where relevant.
- Update redirects to include something for Domo and Tableau.
- Updates the docusaurus version to use the latest release candidate.

2022-07-28 16:39 UTC, ericelsken requested changes

2022-07-28 16:39 UTC, ericelsken commented on docs/reference/admin/user-permissions.md
> +create a "_Rogue Projects_" that only they have access to.
create Rogue Projects
OR
create a Rogue Project
?

2022-07-28 16:39 UTC, ericelsken commented on docs/reference/arguments.md
> +Arguments are comprised of flags and values. The are added at the end of the execution command to run your script in the order they are entered (although generally, the order should not matter). Thes
The are -> They are

2022-07-28 17:25 UTC, ericelsken approved these changes

2022-07-28 19:56 UTC, merged

2022-07-29 15:51 UTC, katthartic reviewed
@blakeburch LOL Welp, it looks like this was merged while I was reviewing it... dunno if you want to consider these changes or not.

2022-07-29 15:51 UTC, katthartic commented on docs/how-tos/environment-variables/access-environment-variables-in-ui.md
> +When a user provides input via [Blueprint Variables](../../reference/blueprints/org-blueprints/blueprint-variables.md), you pass values to your script using [environment variables](../../reference/en
On the first line... should `input` be `inputs` or `an input`?

In the sentence "This how to guide will walk you through the steps to access environment variables." I feel like `how to` should be hyphenated to `how-to`.

2022-07-29 15:51 UTC, katthartic commented on docs/how-tos/vessels/build-vessel-blueprint.md
> +1. At the the top of the information panel, update your Vessel to have a descriptive name. By default, we automatically generate a unique, but undescriptive name.
Don't think you need the comma between `unique` and `but`.

2022-07-29 15:51 UTC, katthartic commented on docs/how-tos/vessels/build-vessel-code.md
> +1. At the the top of the information panel, update your Vessel to have a descriptive name. By default, we automatically generate a unique, but undescriptive name.
Same here about the comma.

2022-07-29 15:51 UTC, katthartic commented on docs/how-tos/vessels/duplicate-vessel.md
>  ### Step 2 - Edit the Duplicate
Do we want to add anything at this point about how to 'store' it for a different Fleet?

2022-07-29 15:51 UTC, katthartic commented on docs/how-tos/vessels/edit-vessel.md
> +Every panel has fields that can be added or edited. These fields will look extremely similar to what you see when initially building a Vessel [with Code](build-vessel-code.md) or [with a Blueprint](b
Not sure this makes as much sense now "These fields will look extremely similar to what you see when initially building a Vessel"

2022-07-29 15:51 UTC, katthartic commented on docs/reference/blueprints/blueprints-overview.md
> +Blueprints are the foundation for most Vessels. They contain the design specifications needed to start building solutions for your organization. As such, they live at the organization level and can b
"As such, they live at the organization level and can be used in any Project. They can either be built by Shipyard staff (as part of the [Blueprint Library](blueprint-library/blueprint-library-overview.md)) or by users in your organization (as an Org Blueprint)." 👉  "They live at the organization level, can be used in any Project and can either be built by Shipyard staff (as part of the [Blueprint Library](blueprint-library/blueprint-library-overview.md)) or by users in your organization (as an Org Blueprint)."

2022-07-29 15:51 UTC, katthartic commented on docs/reference/blueprints/blueprints-overview.md
> +All Blueprints are built using Code. You must select a supported language and provide the necessary code, arguments, environment variables, and packages necessary to make the Blueprint usable. Additi
We we want to make reference to the work-around for unsupported code?

2022-07-29 15:51 UTC, katthartic commented on docs/reference/code/code-overview.md
> +At the top of the code panel, you'll see a field for **File To Run**. In the case of Uploading Code or cloning code from GitHub, this should represent the combined folder and file name of the script
I don't think `Uploading` needs to be capitalized.

2022-07-29 15:51 UTC, katthartic commented on docs/reference/fleets/fleets-overview.md
> +A Fleet is a collection of multiple Vessels working together to tackle one larger job. Fleets are the equivalent of a Workflow or DAG in other orchestration tools.
Since a Fleet can just be one vessel, maybe remove `multiple` from the sentence.

2022-07-29 15:51 UTC, katthartic commented on docs/reference/fleets/fleets-overview.md
> +Fleets can contain any number of Vessels and contain any different type of Vessels \(including a mixture of programming languages and Blueprints\). They can be built in either the [Visual Editor](vis
"Fleets can contain any number of Vessels and contain any different type of Vessels" 👉 "Fleets can contain any number or type of Vessels"

2022-07-29 15:51 UTC, katthartic commented on docs/reference/fleets/visual-editor.md
> +- **Ctrl & Scroll** on the Canvas to zoom in and out.
Want to add anything about the mini-map or zoom buttons?