Adding Tutorial for Creating Blueprint
shipyardapp/Shipyard-Documentation pull request #155
Opened 2022-09-06 20:26 UTC by smjohnsonShipyard

2022-09-07 14:36 UTC, katthartic requested changes

2022-09-07 14:36 UTC, katthartic commented on docs/tutorials/create-organizational-blueprint.md
> +- Pass [environment variables](../reference/environment-variables/environment-variables-overview.md) to your solution.
Is there a reason `variables` is capitalized in one place but not the other?

2022-09-07 14:36 UTC, katthartic commented on docs/tutorials/create-organizational-blueprint.md
> +2. Click the **Add Blueprint** button on the top right of the screen
Add a period?

2022-09-07 14:36 UTC, katthartic commented on docs/tutorials/create-organizational-blueprint.md
> +7. Before we click Add Variable, we need to add the options that the user will have when selecting. Click the **plus sign** to add the following select options:
Before we click Add Variable, we need to add the options that the user will have when selecting. 👉 Before we click **Add Variable**, we need to add the options that the user will have when selecting a file type.

2022-09-07 14:36 UTC, katthartic commented on docs/tutorials/create-organizational-blueprint.md
> +| Default Value  | XLSX                                                        |
You can't indicate a `Default Value` before you've provided options in a `select` variable.

2022-09-07 14:36 UTC, katthartic commented on docs/tutorials/create-organizational-blueprint.md
> +3. For the **hidden value**, enter the name of everyone's favorite pirate: Jack_Sparrow.
LOL

2022-09-19 15:36 UTC, smjohnsonShipyard commented
@blakeburch Should be good for your review now

2022-09-19 21:45 UTC, blakeburch reviewed
@smjohnsonShipyard Small edits requested.

Also for your knowledge, I made small edits at the bottom to make sure:
- Blueprint would be visible.
- Blueprint would have icon.

2022-09-19 21:45 UTC, blakeburch commented on docs/tutorials/create-organizational-blueprint.md
> +id: create-blueprint
General best practice - make sure the id and file name line up exactly. I think `create-blueprint` is best for both.

2022-09-19 21:45 UTC, blakeburch commented on docs/tutorials/create-organizational-blueprint.md
> +# Create Organizational Blueprint Using Python
Organizational -> Org

2022-09-19 21:45 UTC, blakeburch commented on docs/tutorials/create-organizational-blueprint.md
> +- Create a custom [Blueprint](../reference/blueprints/blueprints-overview.md).
a custom -> an org

Trying to consolidate around a single term to not cause confusion.

2022-09-19 21:48 UTC, blakeburch commented on docs/tutorials/create-organizational-blueprint.md
> +In this tutorial, you will walk through the steps required to build a custom Blueprint for your organization using Python. By the end of the tutorial, you'll be able to:
Can you please include some context at the beginning? I found it jarring to just follow instructions not knowing what I was building.

I knew by the end it was to convert other data types to CSV, but it would help to know that before starting.

2022-09-19 21:53 UTC, blakeburch commented
@smjohnsonShipyard Also - a small note for the future. Might be good to somehow link this to the getting started tutorials so the user can actually test it out. It left me a bit empty to set it up but not know how to run it. 

This issue will be compounded by the issue we currently face with users trying to upload/download locally. That might mean flipping the logic so it converts from CSV to any other file type. Thoughts?

2022-09-20 21:17 UTC, blakeburch approved these changes

2022-09-20 21:17 UTC, merged