Change log updates for Aug, Sept, Oct
shipyardapp/Shipyard-Documentation pull request #162
Opened 2022-10-31 15:18 UTC by katthartic

These updates should cover releases v0.303, v0.305, v0.306, v0.307, v0.308, v0.309, v0.310, and v0.313.

2022-10-31 21:54 UTC, forstmeier requested changes
Minor tweaks.

2022-10-31 21:54 UTC, forstmeier commented on docs/changelog.md
> +- Our markdown was messed up, so we got down, cleaned up, and are ready for our checkmark! Markdwon should now display as intended.
Capitalize "markdown" and there's a "Markdwon" typo.

2022-10-31 21:54 UTC, forstmeier commented on docs/changelog.md
> +- Housekeeping did some great work but might have misplaced a few hyperlinks. They have been found and put back where they belong.
:rofl:

2022-10-31 22:05 UTC, katthartic commented
@blakeburch @ericelsken I will need approval on this from one of you to deploy. Eric - Docusaurus wanted me to do some upgrades so that is in here too.

2022-10-31 22:23 UTC, ericelsken approved these changes

2022-10-31 22:29 UTC, katthartic commented
@forstmeier I need your explicit re-approval on this one.

2022-11-01 16:29 UTC, ericelsken approved these changes

2022-11-01 17:27 UTC, forstmeier approved these changes

2022-11-01 17:28 UTC, merged