AWS S3 Documentation Update
shipyardapp/Shipyard-Documentation pull request #164
Opened 2022-11-02 21:43 UTC by wrp801

Added the following blueprints to the documentation:

Amazon S3 - Move or Rename Files
Amazon S3 - Remove Files

2022-11-08 22:10 UTC, blakeburch commented
@wrp801 Leaving this open for us to fill in more gaps this week. Can you:
- Rerun with the latest Blueprint updates
- Make sure to add links to new blueprints on sidebars.js
- Make sure to add links to the new blueprints on the respective overview.md pages.
- Make sure you don't have any (TESTING) Blueprints listed as visibility of "Blueprint Editors". They should be "Hidden". We don't want those to result in docs getting created.

2022-11-15 04:11 UTC, blakeburch requested changes
Small things. Should be easily adjusted before merging early tomorrow morning.

2022-11-15 04:11 UTC, blakeburch commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
1. Always obfuscate any secret values in an image. Good practice to cover ourselves and also "lead by example" when it comes to being secure. You'll need to replace the image with one where the key is obscured.
2. Please make sure this API key you created has been deleted, as it has now been committed to a public repository.

2022-11-15 04:26 UTC, wrp801 commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
I copied this exactly from the API reference here: <https://www.shipyardapp.com/docs/reference/api/> [](edited-with-Axolo)

2022-11-15 04:27 UTC, wrp801 commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
I figured that was good to use since it is already live [](edited-with-Axolo)

2022-11-15 04:29 UTC, blakeburch commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
:thinking_face: Fun. Well then that also needs to be updated. Don’t know how that made it in. [](edited-with-Axolo)

2022-11-15 04:30 UTC, wrp801 commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
I’ll update both [](edited-with-Axolo)

2022-11-15 04:46 UTC, wrp801 commented on docs/blueprint-library/shipyard-api/shipyard-api-authorization.md
> +![API keys generated API key value](../../.gitbook/assets/api-keys-generated-api-key-value.png)
Changes are pushed now [](edited-with-Axolo)

2022-11-15 05:43 UTC, blakeburch approved these changes
Good to merge and push out.

2022-11-15 15:46 UTC, merged