Updated documentation for fleet trigger API
shipyardapp/Shipyard-Documentation pull request #207
Opened 2023-05-10 15:28 UTC by reedcowan

Updated API documentation for the fleet run trigger

2023-05-10 19:33 UTC, blakeburch requested changes
Minor changes.

Additionally, proper case should be used for any Shipyard specific terms. Typically applies to `Fleet(s)` and `Vessel(s)`, but not things like "environment variables" or "triggers"

2023-05-10 19:33 UTC, blakeburch commented on docs/reference/api.md
> +
I would also include that if the environment variable is not provided, the value set in the UI will be used.

2023-05-10 19:33 UTC, blakeburch commented on docs/reference/api.md
> +
Include that it will always trigger the latest version of the Fleet.

2023-05-10 19:33 UTC, blakeburch commented on docs/reference/api.md
> +    'https://api.app.shipyardapp.com/orgs/<org_id>/projects/<project_id>/fleets<fleet_id>/fleetrun',
I think you're missing a `/` in the URL after `fleets`

2023-05-10 19:33 UTC, blakeburch commented on docs/reference/api.md
> +curl https://api.app.shipyardapp.com/orgs/<org_id>/projects/<project_id>/fleets<fleet_id>/fleetrun --header "X-Shipyard-API-KEY: <api_key> -data {json_data}"
I think you're missing a `/` in the URL after `fleets`

2023-05-10 19:33 UTC, blakeburch commented on docs/reference/api.md
> +      "fleet_run_id" : "ad4d4655-91fd-4499-9a1a-06d6e8a433d4"
Please confirm that these are generated UUIDs and do not represent an actual chain of IDs in our platform.

2023-05-11 13:17 UTC, reedcowan commented on docs/reference/api.md
> +      "fleet_run_id" : "ad4d4655-91fd-4499-9a1a-06d6e8a433d4"
These are the same UUIDs found  in the documentation for the successful response of `reference/triggers/webhook-triggers'

2023-05-24 22:06 UTC, blakeburch commented on docs/reference/api.md
> +curl https://api.app.shipyardapp.com/orgs/<org_id>/projects/<project_id>/fleets/<fleet_id>/fleetrun --header "X-Shipyard-API-KEY: <api_key> -data {json_data}"
Endpoint is now `fleetruns`

I also didn't test this, but it looks like your quotes might be off. I think one needs to end after the <api_key> and the other one needs to be wrapped around the {json_data} (but I'm assuming single quotes would be better because JSON uses double quotes typically)

2023-05-24 22:06 UTC, blakeburch commented on docs/reference/api.md
> +    'https://api.app.shipyardapp.com/orgs/<org_id>/projects/<project_id>/fleets/<fleet_id>/fleetrun',
Endpoint is now `fleetruns`

2023-05-24 22:07 UTC, blakeburch commented on docs/reference/api.md
> +}
Need to have tabbed examples, since `null` is not a valid value in Python and instead has to be `None`.

2023-05-24 22:07 UTC, blakeburch commented on docs/reference/api.md
> +3. Replace the left-hand side with the name of the environment variable you'd like to override and the
Emphasize that this is case sensitive.

2023-05-24 22:07 UTC, blakeburch commented on docs/reference/api.md
> +5. If the environment variable override value is `null`, that value will be ignored and not set.
or `None`

2023-05-24 22:09 UTC, blakeburch commented on docs/reference/api.md
> +After a successful fleet run trigger, the fleet will run with the envrionment variables defined in the payload being overridden.
Typo on environment.

2023-05-24 22:13 UTC, blakeburch commented on docs/reference/api.md
> +curl https://api.app.shipyardapp.com/orgs/<org_id>/projects/<project_id>/fleets/<fleet_id>/fleetrun --header "X-Shipyard-API-KEY: <api_key> -data {json_data}"
Also, needs to do curl -X POST, since it is a POST command and it looks like GET just returns a CSV of the logs. Which is strange, because that endpoing is listed as just `runs`. If that has updated to `fleetruns` as well, make sure to update the docs accordingly.

Side note - make sure a user can easily copy/paste these examples and get them running while only substituting `<>` values.

2023-05-24 22:14 UTC, blakeburch commented
@reedcowan Additional feedback after testing the feature. If you can please adjust for launch.

Additionally, same feedback on the capitalization as last time. Typically applies to Fleet(s) and Vessel(s), but not things like "environment variables" or "triggers"

2023-05-30 21:37 UTC, blakeburch approved these changes

2023-05-30 21:37 UTC, merged