AWS authorization documentation [ch2287]
shipyardapp/Shipyard-Documentation pull request #49
Opened 2021-08-09 13:54 UTC by forstmeier

### Description

This adds in authorization instructions for S3, Athena, and Redshift blueprints as well as general information on use and variables.

### Fixes
- ch2287

2021-08-12 20:17 UTC, ericelsken requested changes

2021-08-12 20:17 UTC, ericelsken commented on docs/blueprint-library/amazon-athena.md
> +		i. Add a bucket location for source data in our example we're using the "shipyard-athena-demo" bucket with an optional "data" folder
It think this should be `optional "data/*" folder`. And in the image too. The star at the end allows for any object under the directory. 

Also, you have data here and logs below, is that intentional?

2021-08-12 20:17 UTC, ericelsken commented on docs/blueprint-library/amazon-athena.md
> +		![Glue ARN](../.gitbook/assets/glue-arn.png)
Redo the image without our account id.

2021-08-12 20:17 UTC, ericelsken commented on docs/blueprint-library/amazon-athena.md
> +                "arn:aws:glue:*:972469996956:database/*"
Redo without our account id.

2021-08-13 13:17 UTC, forstmeier commented on docs/blueprint-library/amazon-athena.md
> +		![Add Athena ARN](../.gitbook/assets/add-athena-arn.png)
What can they do with our account ID? Wouldn't they have to [guess role ARNs](https://rhinosecuritylabs.com/aws/aws-iam-user-enumeration/) still in order to potentially do anything?

I can remove it but this feels like overkill.

2021-08-13 13:30 UTC, forstmeier commented on docs/blueprint-library/amazon-athena.md
> +		i. Add a bucket location for source data in our example we're using the "shipyard-athena-demo" bucket with an optional "data" folder
Did it work for you when you generated the ARN including the `/*`? I did not include it in my testing and it worked. If it works with that inclusion I'll make the changes.

Yes, there needed to be separate ARN references otherwise IAM would separate them itself.

2021-09-01 18:04 UTC, blakeburch approved these changes

2021-09-01 18:04 UTC, merged