Add non-supported language documentation/resources [ch2411]
shipyardapp/Shipyard-Documentation pull request #56
Opened 2021-09-02 21:09 UTC by forstmeier

### Description

This adds in instructions on how to build and run a Vessel using Ruby. A pre-zipped file has been provided with the required Bash and Ruby files as a resource for the user to download.

2021-09-02 22:15 UTC, katthartic requested changes

2021-09-02 22:15 UTC, katthartic commented on docs/tutorials/non-supported-language-vessels.md
> +1. Click **Run Now** at the top right of the page. This will schedule your Vessel to run immediately and redirect you to the [Vessel Log](../reference/logs/vessel-logs.md) page.
Immediately after creating a vessel, they will actually get the popup below instead of the screen with **Run Now** on top.
<img width="813" alt="Screen Shot 2021-09-02 at 6 06 51 PM" src="https://user-images.githubusercontent.com/39164291/131922543-71fd3360-80bd-464b-812e-af782022c88d.png">

2021-09-02 23:01 UTC, blakeburch requested changes
2 high level things.

1. I would like to, at the beginning, be very explicit and conceptually explain how we support other languages.
- Any language can be run in Shipyard through Bash.
- Requires the inclusion of a bash script that, at minimum:
   - Installs the language.
   - Installs any external packages for the language.
   - Runs a command to execute your language's script.
- This method means that every time your Vessel runs, it will be installing the language which will take additional time.
2. I would like to include writeup for at least one other language (probably Go). As a result, I would like you to look at creating tabs for the relevant sections so we can expand as needed.
Example of tab setup can be found at `/docs/how-tos/access-environment-variables`

2021-09-07 13:32 UTC, forstmeier commented on docs/tutorials/non-supported-language-vessels.md
> +First, [download this code](../.gitbook/assets/non_supported_language.zip), named `non_supported_language.zip` to your computer without making any changes.
@blakeburch I'll need some guidance on how to replicate - I haven't actually launched Docusaurus locally previously.

2021-09-07 19:33 UTC, katthartic approved these changes

2021-09-13 18:28 UTC, blakeburch approved these changes
Good to go.

2021-09-13 18:28 UTC, merged