Database documentation [ch2426]
shipyardapp/Shipyard-Documentation pull request #58
Opened 2021-09-08 14:34 UTC by forstmeier

### Description

These updates add in the basic steps required to set up users for use in the authorization for database-based blueprints. Since we don't have running servers at the moment, I opted to just recreate the steps from the various database documentation sources I found. It may not be sufficient guidance so we can go over this one more if needed.

2021-09-08 21:51 UTC, ericelsken requested changes

2021-09-08 21:51 UTC, ericelsken commented on docs/blueprint-library/microsoft-sql-server.md
> +
Add something like "You can use an existing user with their credentials or create a new user using the steps below."

2021-09-08 21:51 UTC, ericelsken commented on docs/blueprint-library/mysql.md
> +
Same addition.

2021-09-08 21:51 UTC, ericelsken commented on docs/blueprint-library/mysql.md
> +2. If using the command line, connect to a database by running `USE <database name>`
Is this really required?

2021-09-08 21:51 UTC, ericelsken commented on docs/blueprint-library/postgresql.md
> +
Same addition.

2021-09-08 21:51 UTC, ericelsken commented on docs/blueprint-library/postgresql.md
> +2. If using the command line, connect to a database by running `USE <database name>`
I know this isn't required. Logging in you have to supply a database.

2021-09-13 18:52 UTC, katthartic commented on docs/blueprint-library/microsoft-sql-server.md
> +2. If using the command line, create a login by running `CREATE LOGIN <login value> WITH PASSWORD = '<new password>';`
I find the "if using the command line" a little confusing as there doesn't seem to be another option listed. So, I would either switch it to "In the command line, create a login..." or provide a link to another way of creating these elements such as... https://docs.microsoft.com/en-us/sql/relational-databases/security/authentication-access/create-a-login

2021-09-13 18:52 UTC, katthartic commented on docs/blueprint-library/mysql.md
> +2. If using the command line, connect to a database by running `USE <database name>`
Same thing as in the previous doc, I would change this to "In the command line..." or provide a link to whatever the alternative is.

2021-09-13 18:52 UTC, katthartic commented on docs/blueprint-library/postgresql.md
> +3. If using the command line, create a user by running `CREATE USER <user name> WITH PASSWORD '<new password>';`
Same as previous

2021-09-13 20:01 UTC, blakeburch approved these changes

2021-09-13 20:02 UTC, merged