FTP and SFTP documentation [ch2430]
shipyardapp/Shipyard-Documentation pull request #59
Opened 2021-09-08 15:32 UTC by forstmeier

### Description

FTP and SFTP documentation (nearly identical) have been added. This has not been tested but some basic links for the authorization steps have been included.

2021-09-08 21:55 UTC, ericelsken requested changes

2021-09-08 21:55 UTC, ericelsken commented on docs/blueprint-library/ftp.md
> +The username and password values that are [created when adding a user](https://www.hostmysite.com/support/dedicated/general/filezillauser/index.shtml) (for [FileZilla](https://filezilla-project.org/)
Read and write permissions are required for everything. I.e. just read is required for download, and write for upload. I'd specify this somehow or make a point in each of the blueprint sections what permissions are required.

2021-09-08 21:55 UTC, ericelsken commented on docs/blueprint-library/sftp.md
> +The username and password values that are [created when adding a user](https://www.hostmysite.com/support/dedicated/general/filezillauser/index.shtml) (for [FileZilla](https://filezilla-project.org/)
Same with rw permissions.

2021-09-13 18:36 UTC, katthartic approved these changes

2021-09-14 20:22 UTC, ericelsken commented on docs/reference/blueprint-library/match-type.md
> +The Match Type selected differently affects the Source fields and the Destination fields. These names will differ based on the Blueprint you've selected and the functionality of that Blueprint.
Wording? Should "differently" be at the end of the sentence? Do you mean it's different for source and destination?

2021-09-14 20:56 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +The Match Type selected differently affects the Source fields and the Destination fields. These names will differ based on the Blueprint you've selected and the functionality of that Blueprint.
CC @blakeburch :point_up:

2021-09-14 21:20 UTC, forstmeier reviewed
Left feedback, @blakeburch.

2021-09-14 21:20 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +Leaving the Folder Name blank assumes that the file you want to match to lives in the home directory.
The home directory or the current working directory?

2021-09-14 21:20 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +If you leave **Destination File Name** empty, the original file name that you match to will be kept, stripped of the folder name.
I assume this is true whenever the destination is in Shipyard - is that true for uploads to a vendor?

2021-09-14 21:20 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +|**Destination File Name**| `data.csv`|
Is including `data.csv` correct for "Destination File Name"?

2021-09-14 21:20 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +
Again, are these correct? Should "Destination File Name" be `data_#.csv`?

2021-09-14 22:49 UTC, blakeburch commented on docs/reference/blueprint-library/match-type.md
> +The Match Type selected differently affects the Source fields and the Destination fields. These names will differ based on the Blueprint you've selected and the functionality of that Blueprint.
Poor wording choice. Fixed

2021-09-14 22:51 UTC, blakeburch commented on docs/reference/blueprint-library/match-type.md
> +Leaving the Folder Name blank assumes that the file you want to match to lives in the home directory.
@forstmeier Interchangeable. If they're using a Blueprint, they can't change the working directly, so the current working directory will always be the home directory.

Is your comment mostly that we should consistently say one or the other?

2021-09-14 22:51 UTC, blakeburch commented on docs/reference/blueprint-library/match-type.md
> +If you leave **Destination File Name** empty, the original file name that you match to will be kept, stripped of the folder name.
Yes, it is.

2021-09-14 22:53 UTC, blakeburch commented on docs/reference/blueprint-library/match-type.md
> +|**Destination File Name**| `data.csv`|
Changed this to <empty>. Good catch

2021-09-14 22:55 UTC, blakeburch commented on docs/reference/blueprint-library/match-type.md
> +
This one is correct. It's to show how we do enumeration. If multiple source files are found, the destination file name is enumerated with `_#` before the file extension to ensure that all matched files get stored with unique names.

If we didn't do this behavior automatically, we'd end up in situations where the user accidentally stores all the files under one name. The logic was designed to avoid potential user error.

2021-09-15 12:41 UTC, forstmeier commented on docs/reference/blueprint-library/match-type.md
> +Leaving the Folder Name blank assumes that the file you want to match to lives in the home directory.
@blakeburch More just making sure that the understanding of "working" vs "home" being two different concepts and that they're not conflated.

2021-09-15 18:38 UTC, blakeburch approved these changes

2021-09-15 18:39 UTC, merged

2021-09-15 19:46 UTC, katthartic commented on docs/reference/blueprint-library/match-type.md
> +When using Exact Match, the Blueprint will look for a file that exactly matches (case sensitive) the combination of the provided Source Folder Name and Source File Name. When the folder name and file
Bold Source File Name and Source Folder Name like in Destination below?

2021-09-15 19:46 UTC, katthartic commented on docs/reference/blueprint-library/match-type.md
> +The Blueprint combines the folder and file name to create `reports/monthly/jan_data.csv`. One file is found that matches. Because the Destination File Name is empty, the original file name is kept in
"Blueprint combines the folder and file name to create `reports/monthly/jan_data.csv`." => "Blueprint combines the folder and file name to interpret the source as `reports/monthly/jan_data.csv`."

2021-09-15 19:46 UTC, katthartic commented on docs/reference/blueprint-library/match-type.md
> +The Blueprint combines the folder and file name to create `reports/monthly/jan_data.csv`. One file is found that matches. Because the Destination Folder Name has a value, a folder named `january` is
Same as above.